name: ServerCleaner
main: Artsakhskiyy\ServerCleaner\Main
version: 1.0.0
api: 5.32.1
load: POSTWORLD
author: Artsakhskiyy
description: Plugin for automatic and manual server cleaning...
commands:
  serverclear:
    description: Cleaning server...
    usage: "/serverclear"
    permission: servercleaner.use
permissions:
  servercleaner.use:
    description: Allows the use of the /serverclear command...
    default: op
